### ISSUE TITLE
Ansible 2.10 known-good example playbook request

### ISSUE THREAD

**Issue by kd9cpb** [opengear/opengear.om#14]
Getting an "Unable to automatically determine host network os. Please manually configure ansible_network_os value for this host" error when trying to use the "Get User Information" example playbook in Ansible 2.10 (the system default Ansible in Ubuntu 22.04).

Could we possibly get a known-good example of getting that to work?

See Opengear Support Case 00047014 for more info

**Comment by mattwit** [comment]
What's your playbook and host file look like? You need to add the var ansible_network_os. See sample host file...

`[all:vars]
ansible_network_os=opengear.om.om
ansible_user=root
ansible_password=mypassword!
ansible_httpapi_use_ssl=true
ansible_httpapi_validate_certs=false

[om]
192.168.100.25

[cm]
192.168.100.26`

**Comment by kd9cpb** [comment]
Thanks, that did the trick, I didn't catch the missing 'ansible_network_os=opengear.om.om' earlier. Greatly appreciate the help!

**Comment by mattwit** [comment]
Great! Closing this issue.
