### ISSUE TITLE
Ports Argparse missing name and portnum

### ISSUE THREAD

**Issue by ecrosswhite** [opengear/opengear.om#8]
I found that attempting to modify a port-config I would get an error;

`FAILED! => {"changed": false, "msg": "Unsupported parameters for (basic.py) module: config.ports.name, config.ports.portnum. Supported parameters include: baudrate, databits, escape_char, id, ip_alias, kernel_debug, label, logging_level, mode, parity, pinout, power, sessions, stopbits, terminal_emulation."}`

My task was very basic for testing;

>     - name: Modify ports
>       opengear.om.om_ports:
>         config:
>           ports:
>             - id: "ports-43"
>               label: "label test"
>         state:
>           merged

Digging in I found that `collections/ansible_collections/opengear/om/plugins/module_utils/network/om/argspec/ports/ports.py` needed to have a couple of additions as the facts module seems to return these values when doing a comparison.  Forgive my ignorance as I'm still new to this.  I worked around the issue by adding to argument_spec variable, config.options.ports.options section;

> 'name': {'type': 'str'},
> 'portnum': {'type': 'str'},

Following the addition I was able to run my playbook successfully.

**Comment by mattwit** [comment]
@ecrosswhite Can you create a pull request with your updated _collections/ansible_collections/opengear/om/plugins/module_utils/network/om/argspec/ports/ports.py_  

OR post a code snippet here.

Thanks!

**Comment by ecrosswhite** [comment]
@mattwit Added a pull request to add the items mentioned, https://github.com/opengear/opengear.om/pull/13 

Thank you!

**Comment by mattwit** [comment]
@ecrosswhite Thanks for adding! I tested the updated argspec and still seem to get the same error you're experiencing.  Can you post your full playbook that you tested here?  

Thanks and appreciate your contribution to the repo!!!

**Comment by mattwit** [comment]
Merged PR #13. Closing.
